# Generated by Django 5.0.2 on 2024-03-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
